### ISSUE TITLE
Storing files as mp3

### ISSUE THREAD

**Issue by vojjin** [distriqt/ANE-AudioRecorder#5]
Is there any way to store file as mp3, not m4a? My application is cross-platform (mobile device/web) and I already have mp3 converter but it is just toooo slow, this looks like a better solution, but m4a files are not html5 compatible.

**Comment by marchbold** [comment]
m4a AAC should be html5 compatible? Have you tried playing them?

**Comment by vojjin** [comment]
Problem is that my clients are using mp3 for more than three years. It would be VERY complicated to switch to another format and recompile all old mp3 files to m4a...

**Comment by marchbold** [comment]
Unfortunately mp3 is not supported as a native recording output format. You need to go through a conversion process afterwards, we currently haven't implemented anything in this ANE due to the licensing of the mp3 codec.

If it's something you need you can contact our custom development team at airnativeextensions@distriqt.com

**Comment by ssalbal** [comment]
hi.
is there way the encoded audio data read to bytearray not saving file. i'd like to send auido data to remote server.

**Comment by marchbold** [comment]
@ssalbal You'd need to load the data from the file after recording completes to send the data to a server.

**Comment by argonauta-studio** [comment]
Hi, 
the recorded file can not be played back via NetStream.
The Stream returns a NetStream.Play.StreamNotFound.
It seems that this is an issue with Air Mobile.
Any ideas?
